modLoader="javafml"
loaderVersion="[36,)" 
license="MIT"
[[mods]]
modId="hackmissiles"
version="1.0"
displayName="HackMissiles"
description='''
Mod: HackMissiles - realistic missiles, launchers and defensive systems.
'''
